// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model_gen

type LoginInput struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}
